my365/config/routes.rb
My365::Application.routes.draw do

  root 'views#index'

  get 'views/index' => 'views#index', as: :view

  get 'events/' => 'events#index', as: :events

  get 'events/new' => 'events#new', as: :new_event

  get 'events/:id' => 'events#show', as: :event  

  post 'events/' => 'events#create'
  
  get 'events/:id/edit' => 'events#edit', as: :edit_event

  patch 'events/:id' => 'events#update'

  delete 'events/:id' => 'events#destroy'

  

  get 'userprofiles/' => 'userprofiles#index', as: :userprofiles

  get 'userprofiles/new' => 'userprofiles#new', as: :new_userprofile

  get 'userprofiles/:id' => 'userprofiles#show', as: :userprofile
  
  post 'userprofiles/' => 'userprofiles#create'

  get 'userprofiles/:id/edit' => 'userprofiles#edit', as: :edit_userprofile

  patch 'userprofiles/:id' => 'userprofiles#update'

  delete 'userprofiles/:id' => 'userprofiles#destroy'

end

my365/app/models/event.rb
class Event
  include Mongoid::Document
  field :name, type: String
  field :event, type: String
  field :time, type: Time
  field :date, type: Date
end

my365/app/models/userprofile.rb
class Userprofile
  include Mongoid::Document
  include Mongoid::Timestamps::Short
  field :name, type: String
  field :event, type: String
  field :comment, type: String
end

my365/app/models/view.rb
class View
  include Mongoid::Document
  field :name,  type: String
  field :event, type: String
end

my365/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

my365/app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
	end

	
	def new
		@event = Event.new
	end

		def create 
		@event = Event.new(event_params)
		if @event.save
			render 'new'
		else
			render 'new'
		end
	end
	

	def edit
		@event = Event.find(params[:id])
		
	end


		def update
			@event = Event.find(params[:id])
			if @event.update_attributes(event_params)
				render 'edit'
			else
				render 'index'
			end
		end

	def destroy
	
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	private
	def event_params
		params.require(:event).permit(:name, :event, :digit, :time)
	end




	
end

my365/app/controllers/userprofiles_controller.rb
class UserprofilesController < ApplicationController
	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

		def create 
		@userprofile = Userprofile.new(event_params)
		if @userprofile.save
			redirect_to userprofiles_path
		else
			redirect_to userprofiles_path
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
			@userprofile = Userprofile.find(params[:id])
			if @event.update_attributes(event_params)
				redirect_to userprofile_path

			else
				render 'show'
			end
		end

		def destroy
	
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to userprofile_path
	end


end

my365/app/controllers/views_controller.rb
class ViewsController < ApplicationController

	def index
		@views = View.all
	end

	
end

my365/app/helpers/application_helper.rb
module ApplicationHelper
end

my365/app/helpers/events_helper.rb
module EventsHelper
end

my365/app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

my365/app/views/events/edit.html.erb
<h1>Edit User's profile events list</h1>

<%= form_for @event do |e| %>

	<div class="field">
		<%= e.label :name %><br>
		<%= e.text_field :name %> 
	</div>
	<div class="field">
		<%= e.label :event %><br>
		<%= e.text_area :event %>
	</div>
	<div class="field">
		<%= e.label :digit %><br>
		<%= e.text_area :digit %>
	</div>
	<div class="actions">
		<%= e.submit %>
	</div>
	<% end %>


<%= link_to "Take me back to the complete events", events_path %>

my365/app/views/events/index.html.erb
<h1> here is events/index.html.erb</h1>

<table>
<thead>
  <tr>
   <th>Events</th>
   <th>Number</th>
   
  </tr>
</thead>
<%@events.each do |e| %>
   <tr>
   <td><%= e.event %></td>
   <td><%= e.digit %></td>
   <td><%= link_to "Delete", event_path(e), method: :delete, data: { confirm: "Are you sure you want to delete #{e.event}?"} %></td>


   <td><%= link_to 'Edit', edit_event_path(e) %></td>
   </tr>
<% end %>

</table>


<br>
<%= link_to 'View User Profiles', userprofiles_path %><br>
<%= link_to 'New Event', new_event_path %>

my365/app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for( @event, :url => {:action => :new_event, :controller => :event} ) do |e| %>

	<div class="field">
		<%= e.label :name %><br>
		<%= e.text_field :name %> 
	</div>
	<div class="field">
		<%= e.label :event %><br>
		<%= e.text_area :event %>
	</div>
	<div class="actions">
		<%= e.submit %>
	</div>
	<% end %>

my365/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My365</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	
</head>
<body>

<%= yield %>

</body>
</html>

my365/app/views/userprofiles/edit.html.erb
<h1>Edit your event description!</h1>
<h1><%= @event.event %></h1>

<%= form_for @event do |f| %>
	<div class="field">
		<%= f.label :event %><br>
		<%= f.text_area :event %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>
<br><br>


<%= link_to "Take me back to the finished event", userprofile_path %>

my365/app/views/userprofiles/index.html.erb
<h1> here is userprofiles/index.html.erb</h1>
<h2>User's Name</h2><br>

<table>
<thead>
  <tr>
   <th>Events</th>
   <th>Time of Event</th>
  </tr>
</thead>
<% array = Array(0...@events.length) %>
  
<% array.shuffle! %>
<% arr1 = array[0..4] %>

<% arr1.each do |i| %>

  <%@events.each do |event| %>
    <% if event.digit == i %>
      <tr>
      <td><%= link_to event.event, userprofile_path(event) %></td>
      <td><%= event.c_at %></td>
      <td><%= event.u_at %></td>
     <!--  <td><%= link_to "Add comments or description", new_userprofile_path(event) %></td> -->
      </tr>
    <% end %>
  <% end %>
<% end %>
</table>

<!-- <ul>
  <% @events.each do |show| %>
    <li>
     <%= show.event %>
    <%= link_to show.event, userprofiles_path(show) %>
    </li>
  <% end %>
</ul> -->

my365/app/views/userprofiles/new.html.erb
<h1>Edit your event description!</h1>
<h1><%= @event.event %></h1>
	
<%= form_for @event do |f| %>
	Comments: <%= f.text_field :comment, placeholder: "Change me here" %><br><br>
	Attach an Image to the event:<br><br>
	<%= text_area(:message, "comments here") %>
	<%= f.submit "Event Completed!" %>

<% end %>
<br><br>


<%= link_to "Take me to the finished event", userprofile_path(@userprofile) %>

my365/app/views/userprofiles/show.html.erb
<h1><%= @event.event %></h1>

<p>Here is the most recently clicked event:<p><br>
<show><%= @event.event %></show>
<show><%= @event.u_at %></show>
<br>

<%= link_to "Edit Event", edit_userprofile_path(@event) %>

my365/app/views/views/index.html.erb
<h1>VIEW index</h1>

<%= link_to 'View events', events_path %>